### ISSUE TITLE
Existence

### ISSUE THREAD

**Issue by 0xcaff** [noahrichards/util#4]
Hello,

Thanks for posting this source code here. In a world where we have well tested, well supported tools to generate Makefiles like CMake and GNUAutotools exist, where does this un-tested, un-documented solution fit in?

**Comment by noahrichards** [comment]
I'm struggling to understand what would possess you to reach out blindly to someone on the internet to ask them why they've contributed something publicly. Nobody needs a reason to post something publicly, and you're performing no worthwhile service by opening an _issue_ on GitHub to ask why something exists. Is your general goal to dissuade people from contributing if they don't meet your arbitrary bar of what's worthwhile?

These utilities are really here as backup, and this specific utility is from a professor at my university (maybe yours as well, since GitHub says you are from Rochester), but thanks for reminding me to turn issues off for these projects.
